id: P13D28044
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: es
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    7a09f3d01f2d44398deea9f9fe19fd8d:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    72c035da586446dba3293a8e0e4f8a29:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    3f928a2407a648aab216d1486e48b8fb:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    16f71593940d4037934c1252d6da7850:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    320fc258546643cc962cf11e9c902070:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    b7f991824f934f629267bb11100f0023:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    7108bccca2a74029adc52910a9628e3a:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    c86c016fa34a45ec94ae547a7e70eb04:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    df4de385fdba49f992f3b57371385b55:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    139b4f4d963f40109779e814bf93addf:
      title: The Lament of Rudra
      parent: Confession
    0bc529516f7447bc856746431c9b0695:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    bfe5e62e6b774927903ad80b9bae43ff:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    46fff9ab364b48079ad0b80e09a5173b:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    80ec25c29501488591e84bcceba098bb:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    47b3c225c41e43ecac133042695b841a:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    83d3e0820153450190fa661031756953:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    e16ae4fafb324ef689affb2425ea4306:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    9d80dd65250444d19bbe6026721702e6:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    a073c4960ed94f60b94e285f8402846a:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    2dae17323b68453cbcde54629e777886:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    52ee8a61b2a54abaa369b2c365736dba:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    0da46fd172d34c8493fe421b93b192b8:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    51ce73978ce2415795458e6b5d0f5145:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    144a46b030ae4a0dadadd0c6f994cb82:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    0bc70c835d494abca8b7703b374ca8b3:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    4df3067da4634c3f9ae3beb2e317e1ff:
      title: The Twenty-Eight Commitments
      parent: Tantra
    1e27bfb4c9da4b62ae03f0c75b8c0765:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.941676'
last_modified_at: '2022-02-28T22:46:47.941678'
